# list_comments = [u"Woooow, dope beat",
#                  u"Wooow, dopeeee",
#                  u"You have dope sound",
#                  u"Real stuffff.. You and I have a similar style, maybe a collab?",
#                  u"Real shiiiiit",
#                  u"Real shiiit",
#                  u"I really liked this beat!",
#                  u"I really liked this beat! I have similar beats, let's do a collab",
#                  u"It's vibeee",
#                  u"It's vibee! Maybe collab?",
#                  u"It's perfect! Bro, let's do a collab, write me!",
#                  u"It real dopeeee, let's do a collab, write me!",
#                  u"It's real shiiiit! Bro, let's do a collab, write me on DM!",
#                  u"Woooow, dopeeee sound!! I have similar beats, I would appreciate it if you subscribe to me too",
#                  u"Bussiiiin",
#                  u"Bussin Maybe collab?",
#                  u"Niceee beat my bro",
#                  u"Amazing! Bro, I have similar beats, I would appreciate it if you subscribe to me too",
#                  u"Wooow, this is dopeeee I have similar beats, let's do a collab",
#                  u"Write to me in DM, I really want to work with you!!",
#                  u"Real stuffff",
#                  u"That's amazing man!!",
#                  u"Nice beats broo! Maybe a collab?",
#                  u"Dopeee, keep it up!",
#                  u"Dope beat! Maybe a collab?",
#                  u"Keep it up",
#                  u"Niceeee"]


list_comments = [u"Woooow, dope beat💫💫",
                 u"Wooow, dopeeee🔥🤤",
                 u"You have dope sound🔥🔥",
                 u"Real stuffff🔥💫 You and I have a similar style, maybe a collab?",
                 u"Real shiiiiit🚀🚀🔥",
                 u"Real shiiit🔥🔥",
                 u"I really liked this beat!🔥🔥",
                 u"I really liked this beat!🔥🤤🤤 I have similar beats, let's do a collab",
                 u"It's vibeee🤤🤤",
                 u"It's vibe🤤🔥 Maybe collab?",
                 u"It's perfect🔥🔥🚀 Bro, let's do a collab, write me!",
                 u"It real dopeeee🔥 Let's do a collab, write me!",
                 u"It's real shiiiit🥶💯 Bro, let's do a collab, write me on DM!",
                 u"Woooow, dopeeee sound💯🤤 I have similar beats, I would appreciate it if you subscribe to me too",
                 u"Bussiiiin🥶",
                 u"Bussin🥶🥶💯 Maybe collab?",
                 u"Niceee beat💯🔥",
                 u"Amazing💫\nBro, I have similar beats, I would appreciate it if you subscribe to me too",
                 u"Wooow, this is dopeeee🔥🔥 I have similar beats, let's do a collab",
                 u"Write to me in DM, I really want to work with you!!",
                 u"Real stuffff🔥🔥",
                 u"That's amazing man!!💯🔥🔥",
                 u"Nice beats broo!💯 Maybe a collab?",
                 u"Dopeee, keep it up🤘🏼🚀🔥",
                 u"Dope beat💯🤤 Maybe a collab?",
                 u"Keep it up🔥🔥",
                 u"Niceeee"]